### ISSUE TITLE
Change, remotes and GitHub

### ISSUE THREAD

**Issue by Sabryr** [coderefinery/git-intro#10]
The Remotes and GitHub section focuses more on Bare repositories on a local collaboration. I do not think we use these in real life anymore. 
I would like to use a gitbub based example I have, where I  add the participants as collaborators (not the fork/pull cycle). User can use a username/password login (ssh key setup not a must). I believe this will be more realistic. If there is not objection, I will port my power-point to this document.

**Comment by bast** [comment]
I agree that an example with GitHub is more realistic than a local bare repo - from my point of view please go ahead.

**Comment by bast** [comment]
I have now considerably simplified this section. Resolving this issue.
