### ISSUE TITLE
Reorder episodes

### ISSUE THREAD

**Issue by bast** [coderefinery/git-intro#101]
From:
```
motivation
start-existing-repo
basics
undoing
break
branches
remotes
break
conflicts
staging-area
under-the-hood
interrupted
aliases
```
To:
```
motivation
start-existing-repo
basics
break
undoing
staging-area
break
aliases
branches
conflicts
remotes
interrupted
under-the-hood
```

**Comment by rkdarst** [comment]
+1

undoing and staging-area may be a bit short to be the only thing
between two breaks, depending on what final contents is.

**Comment by bast** [comment]
I agree that it is too little. We will later readjust. Step two will be to set realistic times for each episode and then see how it fits with breaks.
