### ISSUE TITLE
Adjust timings and breaks

### ISSUE THREAD

**Issue by bast** [coderefinery/git-intro#102]
We will do this at the very end, once most of other patches are in.

**Comment by bast** [comment]
... once we have defined realistic time expectations for each episode.

**Comment by rkdarst** [comment]
My initial suggestions based on current state:  (numbers in parentheses is delta compared to current):

- Motivation: 10 minutes (-5)
- in-browser: 20 minutes (-5)
- basics: teaching 20, exercises 25 (+5)
- undoing: teaching, 10, exercises, 10 (-15)
- staging: teaching 10, exercises 10 (-5), assuming not doing advanced
- aliases: teaching 5, exercises 5 (-5)
- branching and merging: same
- conflict resolution: teaching 15, exercises 15 (+5)
- sharing repos: same
- interrupted work: teaching 5, exercises 5 (maybe 10). (+0 or +5)
- under the hood: same

**Comment by bast** [comment]
Sounds very good - let me apply this in a minute. Tomorrow I might shift one or two things.
