### ISSUE TITLE
Discuss necessary level of complexity

### ISSUE THREAD

**Issue by bast** [coderefinery/git-intro#105]
At some point, mention what level of complexity is necessary for each project.  E.g. simple personal project, committing on master is OK, use branches only if you think you might be interrupted. Project with few people and willing to accept things breaking, some master commits/somefeature branches might be reasonable.  At what point does it get large enough you want to start real review processes and PR-based model?  This can be discussed both in sections, at end of lesson, and at end of git collaboration.

Thanks to @rkdarst for this good suggestion.

**Comment by rkdarst** [comment]
And lowest level of complexity is `git commit -a`, which in most cases
should only be used when a project is so new that every change
necessarily touches everything... but even then, `git commit -p` to
double check yourself when commiting!
