### ISSUE TITLE
the git revert example may lead to conflict

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/git-intro#126]
in episode 5, "undoing things", the `git revert` example suggests doing two commits and reverting the former. This leads to a conflict if the same line is edited, e.g. if a new line is added in each of the commits at the end of one of the tracked files.

Not sure if it's best to warn about this (which might be confusing since conflicts haven't been covered yet), or to demonstrate a simpler `git revert` example

**Comment by bast** [comment]
It would be better to have a "bulletproof" example which "cannot" conflict at this stage to not confuse too much.

**Comment by wikfeldt** [comment]
yeah i agree, will change it

**Comment by wikfeldt** [comment]
solved in 5ea1c53b99d06b8433200615dd2e3901ad07d43e
