### ISSUE TITLE
“Git-refresher” / “git-basics” lesson

### ISSUE THREAD

**Issue by bast** [coderefinery/git-intro#143]
[this is taken from our team meeting notes]

- start by cloning code project (e.g. word-count). It will contain some bugs. 
- We start by adding and committing to get experience and muscle memory. 
- We then discover the bug, and start branching off to fix it. We then encounter merge conflicts and practice solving them 
- we merge git-archeology into this lesson into an episode called “history” which emphasizes the importance of git history (git log (with various flags), git blame, git grep), and show git-bisect as a useful tool to find the bug.
- Towards end, we emphasize that if you need to start from scratch, you simply do git-init and git-add and get back to what we’ve been practicing.
- "rm -rf .git" and demonstrate starting from scratch
- Use now-unlinked repository as starting point for git-collab

**Comment by wikfeldt** [comment]
we now have a git-refresher lesson, and I think we have abandoned the idea to use a real code project for this lesson. Git-archeology is already merged into git-intro
So i'm closing this issue
