### ISSUE TITLE
describe that if participants clone recipe-branching repo then remote branches will not be visible 

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/git-intro#156]
emphasize that `git branch -r` is needed to show remote branches,
and that e.g. `git checkout experiment` sets up local branch tracking remote origin/experiment branch

**Comment by Sabryr** [comment]
May be "git branch -a" should be used thoughout

**Comment by rkdarst** [comment]
`git graph` the remote branches, but that's not too relevant.

More important: `git merge experiment` doesn't work until local branch is made.
