### ISSUE TITLE
here we clone the word-count repo, but later we require participants to fork it

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/git-intro#157]
In the reproducibility and documentation lessons, learners are asked to fork and clone coderefinery/word-count (and it's necessary in documentation), but in git-intro we clone it for the archeology episode. 
This is somewhat confusing

**Comment by annefou** [comment]
in the documentation lesson, we fork it...

**Comment by bast** [comment]
Nowadays we don't fork the repo in the documentation lesson but generate from a template.

I personally don't see the problem of cloning here and close this issue.
