### ISSUE TITLE
Git staging example: 

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/git-intro#170]
In https://github.com/coderefinery/git-intro/pull/148/commits/be801217a5fcff6ed54c4639a651be9fb79e5153, the git staging example was made simpler.  While presenting, I don't think it was quite as good (note that I am extremely biased because I helped come up with the other example).

There isn't a as goon an analogy to the working directory: you aren't incrementally making new changes to pack and seal, everything is just there.  It could be "bring a lot of junk to your desk (working directory) to pack (stage) and seal (commit)", but that's a bit artificial. And you can have multiple boxes open at once, packing them all simultaneously (I couldn't explain why you had to seal one before working on the next).

While the shopping basket analogy, multiple receipts is something people often know (and has to be done in sequence, you can't have multiple open transactions), there's a clear working directory (walking around the store), clear analogy about walking through the store twice vs once and staging.  You _can_ have multiple staging areas open at once when shopping but that was easy enough to gloss over.

What do you think?  I could try to write it even simpler and remove some unnecessary stuff from it.

**Comment by wikfeldt** [comment]
I'm fine with reverting back to the conveyor belt analogy. Once I think I managed to confuse learners with the conveyor belt, but most likely that was because I didn't explain it right. I see your point about having an analogy for the working directory. Perhaps change back to conveyor belt and make it extra clear so that neither instructors nor learners get confused!

**Comment by bast** [comment]
I liked both analogies but I got now convinced that the shopping basket one is even closer.

**Comment by bast** [comment]
I thought more about this: in the shopping basket analogy it is also easier to motivate that something might need to get reverted. I though how this could look with moving boxes and could not come up with a convincing example:
- would I like to send some of my boxes back? unlikely.
- would I get somebody else's moving box accidentally delivered? unlikely.

I will either go back to shopping basket or offer both and the instructor could choose their favorite analogy?
