### ISSUE TITLE
Duplicate exercise in 02-bacics and 04-staging-area (incrementally commit)

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/git-intro#172]
02-basics has an exercise where you make two changes in different files, stage them separately, and commit ("Exercise: record changes")

04-staging-area has an exercise where you make two changes in different files, stage one of them, examine the situation, and go back. ("Exercise: Using the staging area")

These felt quite similar when doing them, even though the end is different.  Looking back at it, theoretically it feels good but the way I presented felt a bit déjà vu-ish.  Any ideas what to do?

Somewhat related: When preseting 02-bacisc, the very first technical section ("Recording a snapshot with Git") forced me to mention staging in some sense, but then we actually got to it in 04-staging-area.  Ideas?

See also #134,  but I think that's a different issue going by page titles.

**Comment by bast** [comment]
I have felt this repetitiveness in a few workshops: "didn't we do this already 30 mins ago?". Since our time is very limited, I think we should condense this to only exercising this once.

**Comment by bast** [comment]
Duplicate with #193. Closing this one. Following up in the other one.
