### ISSUE TITLE
missing difftools configuration

### ISSUE THREAD

**Issue by avaldebe** [coderefinery/git-intro#178]
On [optional exercise visual diff tools], there is no mention on how to setup a difftool.
A new user that needs introduction to diftool would also need to know how to configure git to use e.g. meld. Therefore, I suggest the following line to be added on the exercise:

```bash
git config --global diff.tool meld
```

[optional exercise visual diff tools]: https://github.com/coderefinery/git-intro/blob/gh-pages/_episodes/02-basics.md#optional-exercise-visual-diff-tools

**Comment by bast** [comment]
Thanks!
