### ISSUE TITLE
Make it possible to show git revert in the same example

### ISSUE THREAD

**Issue by bast** [coderefinery/git-intro#179]
In Oslo we have created a new repo to demo reverting but I would prefer if we stay in the same example to minimize confusion and explaining. Possibly we need to adapt the material for that.

**Comment by Sabryr** [comment]
I would like to not to create a new temporary demo. What i wanted was to make the graph identical to what is in the material. Yes, So a solution would be to adapt the material.

**Comment by bast** [comment]
In my understanding this is already in the material: https://coderefinery.github.io/git-intro/05-undoing/#clean-history. Closing.
