### ISSUE TITLE
"Mortal combat" in conflict resolution images look apparently too scary

### ISSUE THREAD

**Issue by bast** [coderefinery/git-intro#180]
Let's consider throwing them away. Their goal was not to scare people or show that conflicts are bad or scary. Conflicts are a good thing.

The goal was to have some fun and lighten things up but I don't think anybody else than me thinks these are fun and then it's better if they go into Git history.

**Comment by wikfeldt** [comment]
I've never noticed any negative reactions to having these images, and I like them too! But if you have reasons to believe they're counterproductive then into git history they go...

**Comment by bast** [comment]
I think Sabry does not like them and mentions this every time and that is totally fair not to like them :-) and I don't want to put Sabry into a position to present something that he does not like.

**Comment by rkdarst** [comment]
I also thought about the conflict and remote image.  There's nothing
wrong with them, but it does give an impression that we are all
nerds.  From that aspect, Mortal Kombat is funny, but I wonder how it
appears to others.

Are there any good less nerdy pop culture references to include
throughout our material?

note: I'm not saying it *should* be removed, just my considerations.

**Comment by bast** [comment]
I had the same impression that this is niche-funny only.

**Comment by Sabryr** [comment]
I agree that this lightens the moment before showing something scary, so do not mind at all to keep the image (I am all in for jokes). My comments were not really criticising the image but a possible misinterpretation.  My intention was to clarify "conflicts" are not a place to "fight" but to "negotiate". i.e. it is a place for "dialogue" not a place to "debate or fight"  (which is counter productive in collaboration). To explain more, this is place where there more than one possible solution exists for an issue, and mine is one of them, should I stand my ground and defend it ? or should I make a compromise so the final out come would be a greater one ?

**Comment by bast** [comment]
I will remove the mortal combat images and replace them by something more helpful.
