### ISSUE TITLE
History inspection episode uses word-count example - too early?

### ISSUE THREAD

**Issue by bast** [coderefinery/git-intro#181]
And this is good that we use own examples but at that moment in time, this has not been introduced. We then grep for zipf but at this moment in time we have no idea what this is. So I am not sure this example is relatable at this point and perhaps we should rather inspect the history of the recipe?

**Comment by bast** [comment]
Same impression today:
- what is this word-count repo we clone?
- why are we grepping for "Zipf"?
- what is "Zipf"?

A better relateable example would be nice. Here we are trying to make a link to something we don't know yet.

**Comment by bast** [comment]
At the latest when I will teach this lesson, I will propose a change. This example did not work for me here.

**Comment by wikfeldt** [comment]
i'm wondering what an alternative could be though. word-count has the advantage that it's a realistic code project, and so the archeology we do will be similar to how participants will be using the process later. Any other realistic example might be equally artificial in this context, so that leaves only our guacamole recipe as a repo to try the history-digging commands on, but that wouldn't be very realistic or "interesting". Any ideas for a better alternative?

**Comment by bast** [comment]
I would look for something from the R world. So that we have at least something to show to the R crowd.

**Comment by wikfeldt** [comment]
that would be one way to cater to the R crowd. The drawback is that it wouldn't be as relatable for the pythonistas who usually make up a majority of the participants

**Comment by bast** [comment]
I agree that jumping to an unknown repository is in any case a jump. Maybe we can make it an exercise where we let participants inspect history and offer 2-3 repositories and participants take the one that is closest to their ecosystem?

**Comment by wikfeldt** [comment]
yeah that sounds good! I think I'll make it into an exercise. First the instructor can show how the commands work (no type-along), and then participants repeat the steps on repos of own choice

**Comment by bast** [comment]
Maybe we can make participants find something to have a bit of a challenge. Easter egg hunt with Git.
- find out when a change got introduced
- find out how long a bug has been there
- find out why a line was added
...

**Comment by wikfeldt** [comment]
sounds really fun, but that again requires a specific repository, right? And if not word-count, then what?

**Comment by bast** [comment]
We need good examples and I will try to contribute one of them. Word count can also be one of them. It can also remain word count but in the present form how we present it, it fell from the sky without enough context.

**Comment by wikfeldt** [comment]
maybe we can (greatly) simplify the word-count project in a new "archeology-exercise" repo, basically just keep the source files, and add lots of small commits and 1-2 bugs somewhere and use this new repo in all the archeology episode. This will take some work but would both make this episode more coherent and create a first introduction to the word-count project

**Comment by bast** [comment]
I agree that we can probably unify all archaeology exercises in one repository. I can work on it for the Stockholm workshop where I will do Git intro.

For the actual example I am personally still undecided between:
- real examples from different languages (probably too complex)
- word count: nice but also quite Python-specific
- something language-independent like a recipe repo but perhaps that's too unreal

**Comment by bast** [comment]
I will create a history inspection exercise where we explore real life projects and participants will be able to choose between Python, C++, R.

I will provide very little explanation and let participants experience `git grep`, `git blame`, `git show`, and creating branches in the past.

I think this will be more fun than us explaining steps and using a constructed repository which at this point is not more familiar than any other example.

**Comment by bast** [comment]
After more thought I will go only for one language example (it does not really matter here) and encourage group work.

**Comment by bast** [comment]
After a lot of searching I think this is a good example repo: https://github.com/tidyverse/rvest
(I had to find a repo which was not too huge to avoid long cloning and where we can search for something which was really introduced and not only moved)
