### ISSUE TITLE
We have two recipe repositories, keep one

### ISSUE THREAD

**Issue by bast** [coderefinery/git-intro#183]
There are:
- https://github.com/coderefinery/recipe
- https://github.com/coderefinery/guacamole

We need to git-grep where they are used and consolidate into only one.

**Comment by Sabryr** [comment]
Only https://github.com/coderefinery/recipe is used

**Comment by bast** [comment]
So the other one is deleted?

**Comment by bast** [comment]
No it's not - reopening.

**Comment by Sabryr** [comment]
I do not have permission to delete that. I can confirm it is not use in the text.
 git grep "https://github.com/coderefinery/guacamole"
returns nothing.

**Comment by bast** [comment]
Is it used in some other lesson @wikfeldt? If not, I will remove it later and then close the issue.

**Comment by wikfeldt** [comment]
the guacamole recipe was used in the git-branch-design lesson. I have now updated it in 20a0dd6a48cb64075885bea88391bb593bb5a616
so this issue can be closed

**Comment by bast** [comment]
So I can remove https://github.com/coderefinery/guacamole?

**Comment by wikfeldt** [comment]
sorry prematurely closed the issue. Yes AFAIK the guacamole repo can be removed
