### ISSUE TITLE
Participants need to be able to access both Git and Python in the same terminal

### ISSUE THREAD

**Issue by bast** [coderefinery/git-intro#185]
- We have instructions but they are easy to overlook.
- We don't have instructions on how to verify.
- We have instructions on how to fix this (make Python visible in Git bash) but these are almost impossible to find.
- It would be good to also provide instructions on how to make Git visible in Anaconda prompt.

I place this issue here because issues in https://github.com/coderefinery/installation/issues seem to be ignored.

**Comment by wikfeldt** [comment]
masterfully tackled in https://github.com/coderefinery/installation/pull/85
closing issue
