### ISSUE TITLE
Make clear when to type and when not

### ISSUE THREAD

**Issue by bast** [coderefinery/git-intro#187]
Observed in Aalborg:
> There were a few occassions when it was not exactly clear if participants should be typing along or not

**Comment by bast** [comment]
Maybe we need better visual help and/or a note in the instructor guide.

**Comment by bast** [comment]
Hopefully after updating to latest https://github.com/carpentries/styles this will become easier for us to highlight.

**Comment by Sabryr** [comment]
IMO Message should be visual, Two suggestions.
1. zenity --info --text="Type with me"   # zenity is coming with Ubuntu these days and can be installed on other shells. This pops up a message box and can be be closed with a button. 

2. Change the background color of the terminal when the leaner should type alone 

Both this could be activated and deactivate with bash aliases

**Comment by bast** [comment]
Definitely visual. I was thinking in the material itself but good idea to also indicate it somehow in the terminal.

**Comment by Sabryr** [comment]
Some of this can be conveyed in the material, not all. The reason being depending on the Audience, instructor and how the day has been so far might may change the way coding happens.

**Comment by Sabryr** [comment]
Is having different background colors for the code block, is an solution ?

**Comment by Sabryr** [comment]
github pages change background of color "code blocks" did not give me anything. 

This you should watch instructors terminal 

This you should type-along 

<p  style="background-color:powderblue;">
```shell
$ git add somefile.txt
$ git commit

$ git add file.txt anotherfile.txt
$ git commit
```
</p>

**Comment by Sabryr** [comment]
I will try a visual guide during https://coderefinery.github.io/2021-05-10-workshop/. If works we can adopt

**Comment by bast** [comment]
We have moved to sphinx. I am now reworking the material and will try to condense and make this clearer with more instructor notes which are now not in a different file but in the same material.

If this is then still an issue, we can reopen.
