### ISSUE TITLE
is the "Clean history" section at end of undoing episode confusing?

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/git-intro#196]
there's a section at the end of undoing episode where learners are asked to do a `git reset --hard`. Is this really necessary, or worth the possible confusion? I know i've taught this without everyone cleaning their histories and don't remember any problems with that

**Comment by bast** [comment]
https://coderefinery.github.io/git-intro/05-undoing/#clean-history

**Comment by bast** [comment]
Motivation for this was to allow participants to experiment with the staging and "mess things up" but later be able to continue with branching and see the same things when inspecting `git graph`. The reset command is there introduced in passing. I agree that it can create confusion. But it is also important that participants see the same thing as on the big screen (they often notice the tiniest differences and ask about it).

**Comment by wikfeldt** [comment]
ok maybe keep the section then but make sure to describe its purpose

**Comment by bast** [comment]
If we should describe its purpose, or follow-up, please create a follow-up issue. You can assign it to me. But otherwise all suggestions in a closed issue I will likely forget :-)

**Comment by wikfeldt** [comment]
you're right, i was creating the issue in my brain but that's a bit too optimistic

**Comment by bast** [comment]
Thanks :-)
