### ISSUE TITLE
Comments on git-intro

### ISSUE THREAD

**Issue by Vathasav** [coderefinery/git-intro#2]
While going through the git-intro, I felt that mentioning few additional things may be important. Perhaps, @Jyrsa  has already thought about them and is planning to discuss while lecturing. 

* Something about why sharing software and data is getting more popular in research context and github being a popular platform for sharing software
* Why Git over other VCS? Difference between Distributed VCS and centralized VCS? Radovan is talking about Distributed VCS in the advanced session, but in my opinion it may be helpful to briefly mention about distributed VCS in the introduction session. 
* Mentioning difference between master and Head? I noticed that people often confuse about master and head.

Typos:

Have you ever had to start working software written by others? --> Have you ever had to start working on software written by others?

You can avoid using one one by always passing messages on the command line, but that limits you in the long run --> You can avoid using one by always passing messages on the command line, but that limits you in the long run.

**Comment by bast** [comment]
Good points. For typos I recommend to file PRs directly.

As to centralized/distributed: You can mention that distributed gives more flexibility to delegate quality control and also allows external contributions from people without write access.
