### ISSUE TITLE
git reset HEAD vs git restore

### ISSUE THREAD

**Issue by bast** [coderefinery/git-intro#203]
One workshop participant unstaged with git restore since this was recommended by Git command line. Let's check that our material is up to date. For me this was a new command.

**Comment by ashwinvis** [comment]
git-restore is a new command is nice, indeed. There is also git-switch which allows one to make a branch out commits on a detached HEAD. But a drawbacks are:

1. Only available in the newest git versions
2. The man pages say:
> THIS COMMAND IS EXPERIMENTAL. THE BEHAVIOR MAY CHANGE.

cf.: https://www.git-scm.com/docs/git-restore, https://www.git-scm.com/docs/git-switch

**Comment by bast** [comment]
Thanks! I did not know about `git switch`. I will mention these two in the text but mention that these commands are new.

**Comment by bast** [comment]
I am not too worried about "THIS COMMAND IS EXPERIMENTAL. THE BEHAVIOR MAY CHANGE." since these commands are already advertised by the command line interface.

**Comment by ashwinvis** [comment]
True and especially since the feature has shipped. It could be an old message in the manual. I must say I really liked those commands when I used Arch Linux, but I miss it since I am stuck with git 2.17.1 on Ubuntu LTS 18.04.

**Comment by bast** [comment]
Ah. So on Ubuntu `git restore` and `git switch` are both not there? I was about to push a change but maybe I should wait. [I am also on Arch]

**Comment by ashwinvis** [comment]
It seems to me (from the commit above) the feature is available on git 2.23 and above from the commit message. Certainly not available on Ubuntu LTS and most likely not on [Ubuntu Eoan which has git 2.20.1](https://packages.ubuntu.com/search?suite=eoan&searchon=names&keywords=git).

**Comment by bast** [comment]
OK thank you. Then I better not push my change. Let's wait a bit then. But looking forward to having these commands generally available. More intuitive and more safe. I will push a change where I announce in the material how they will be called in future.

**Comment by ashwinvis** [comment]
OK, I managed to install [latest stable git via a PPA](https://www.git-scm.com/download/linux). `conda install git` is also another possibility.

**Comment by rkdarst** [comment]
For the record 2.23 was released on 2019-08-16, so by my standards I wouldn't teach until 2021 or 2022 (otherwise, it just gets more confusing - I am very conservative in teaching, it's not a good bet to expecting everyone to have the latest tools).  I added a note to the instructors guide.
