### ISSUE TITLE
the advanced exercise in staging episode needs a fix

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/git-intro#204]
https://github.com/coderefinery/git-intro/blob/gh-pages/_episodes/04-staging-area.md#optional-interactive-staging

it doesn't really work as it is, because even if participants edit multiple lines, Git will during interactive staging interpret these changes as one chunk in the instructions.txt file (so no way to selectively stage chunks). We have to figure out the easiest way to create modifications that `git add -p` or `git add -i` will be able to split into chunks

**Comment by bast** [comment]
Provided participants "Make sure that they are separated by at least one unmodified line", they can split hunks by pressing "s". So in my opinion this example works and is a good example. But I will emphasize these in the instructions.
