### ISSUE TITLE
every standard exercise should be followed by advanced exercise

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/git-intro#205]
this is to keep the advanced participants interested.
this applies also to all other lessons

**Comment by wikfeldt** [comment]
consider also to have solutions to all advanced exercises, since typically we don't go through them

**Comment by bast** [comment]
I will add few exercises but I don't think I will be able to add solution to all so I unassigned this issue.

**Comment by bast** [comment]
I think this is now the case. If not, we can create more focused issues.
