### ISSUE TITLE
link to "Rain"

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/git-intro#206]
a "software art" project visualizing commit messages on github as rainfall:
https://travis.durieux.me/rain.html

might be fun to mention when discussing commit messages

**Comment by bast** [comment]
Hypnotic. Great project!

**Comment by rkdarst** [comment]
Really neat, but be careful if you leave it on in backgrounded
tab. Commits still appear at the top, but there's no vertical motion
so they accumulate!

**Comment by bast** [comment]
I just visited the page again after a while and nothing seems to be happening. Also there is no explanation on the website so it might look confusing. Right now all I see there is a static Travis worker "head".

**Comment by bast** [comment]
It's raining again.

**Comment by rkdarst** [comment]
Site gives 502 bad gateway from cloudflare now.  If we try again in a month and it doesn't work, then I guess we can close this...

**Comment by bast** [comment]
Out of many tries I have seen this page working once or twice. It seems to have been a one-time thing and to me looks unsupported. Closing.
