### ISSUE TITLE
move references and links to final episode

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/git-intro#209]
this was a comment from a post-workshop survey answer, which said it would be more convenient for later purposes to have all links collected at the end or in "references" episode. 
Sounds like a good idea to me, and should probably be done in other lessons too

**Comment by rkdarst** [comment]
Does this mean every non-trivial link within the text, such as what is below.  Below, I pasted a bunch of different links I found randomly in the text - which ones should or shouldn't be included?

I like the idea of `reference.md` having all the most important links that can be browsed later.
-----

- [Commits with multiple authors](https://help.github.com/articles/creating-a-c\
ommit-with-multiple-authors/)
- ["My favourite Git commit"](https://fatbusinessman.com/2019/my-favourite-git-\
commit)
- ["On commit messages"](https://who-t.blogspot.com/2009/12/on-commit-messages.\
html)
- ["How to Write a Git Commit Message"](https://chris.beams.io/posts/git-commit\
/)

[shell glob syntax](https://en.wikipedia.org/wiki/Glob_(programming))
[documentation](https://git-scm.com/docs/gitignore)

- [GitHub Desktop](https://desktop.github.com)
- [SourceTree](https://www.sourcetreeapp.com)
- [List of third-party GUIs](https://git-scm.com/downloads/guis)

- See [merge strategies](https://git-scm.com/docs/merge-strategies).

> For more information about tags see for example
> [the Pro Git book](https://git-scm.com/book/en/v2/Git-Basics-Tagging) chapter\
 on the
> subject.

**Comment by bast** [comment]
I am not sure about this. I find it more useful to have a link close to where we talk about it.

Another problem is that in this lesson we traditionally run short of time and then we might not even have the time to mention that there is an extra episode with all links.

My goal now is to make the overall text shorter and clearer and sharper and make the links easier to find. Also the move to Sphinx helps with this.
