### ISSUE TITLE
Provide dependacy check for Jekyll instaltion 

### ISSUE THREAD

**Issue by Sabryr** [coderefinery/git-intro#21]
If the proper dependencies are not met Jekyll installation could waste a lot of time. So include list of dependencies. Sabry will do this for Ubuntu  17.04

**Comment by bast** [comment]
`sudo apt-get install jekyll` did not work?

**Comment by Sabryr** [comment]
It did not install all dependences. Casing errors like "Gem::Ext::BuildError...failed native extensions" ....an error occurred while installing,,,. 
I will keep the procedure in my private repo so can be integrated later if needed. I have removed the branch to keep things clean.

**Comment by bast** [comment]
But will you share your docs? Please do. There is no doubt that these are useful for others. The only doubt was whether this is the right place. Please share them.

**Comment by Sabryr** [comment]
Of course, I am not a Ruby person and notes were to start from nothing. My principle is one should not need to know Python to learn Git, and does not need to know Jetty to contribute to the course materiel.
 I will find a suitable place (not a priority at the moment though) , but now I am more focused on the course materiel  it self.

**Comment by bast** [comment]
I agree but reiterate: your doc is useful, please share it.
