### ISSUE TITLE
add link to git history browser

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/git-intro#212]
https://githistory.xyz/
thanks to @ashwinvis !

**Comment by ashwinvis** [comment]
Demo: https://github.githistory.xyz/coderefinery/git-intro/blob/gh-pages/_episodes/01-motivation.md

**Comment by bast** [comment]
Amazing!

**Comment by bast** [comment]
I will build this into the history inspection but might be nice to also show in the motivation @annefou?

**Comment by bast** [comment]
I wanted to add this to the material but it started crashing on me today. Need to check this later.
