### ISSUE TITLE
possibly confusing picture to explain conflicts

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/git-intro#214]
the figure under https://coderefinery.github.io/git-intro-stockholm/08-conflicts/#conflict-resolution 
might remind learners of git commit boxes.
Perhaps something like
```
       ________
____/________\____        
      \_____________/
```
decorated by the recipe images would be clearer (thanks @aswinvis)

**Comment by bast** [comment]
In a sense these can be looked at either as files or as Git commit boxes so I am not sure I see the problem. I will leave this at the moment but pull requests for clearer pictures welcome.
