### ISSUE TITLE
Inspecting history: add hint to find a line in a git annotate output

### ISSUE THREAD

**Issue by ashwinvis** [coderefinery/git-intro#215]
Improvements:

* Paginate `less` output `export LESS="-F"`

Hints:

* Pipe `git annotate  .... | grep "No links matched that expression"`
* Search in `less` using `/No links`

**Comment by ashwinvis** [comment]
https://coderefinery.github.io/git-intro-stockholm/10-archeology/

**Comment by bast** [comment]
Thanks! This was indeed unnecessarily difficult and I did not notice it because I am so used to these tools.

**Comment by ashwinvis** [comment]
Another related question was "Can `git grep` be used to search for a string though history?". [So many solutions!](https://stackoverflow.com/questions/2928584/how-to-grep-search-committed-code-in-the-git-history)

**Comment by rkdarst** [comment]
#230 tries to resolve this by mentioning searching in `less` in the `git annotate` section, which is where it seems relevant.  I'm not sure how `export LESS="-F"`: `--quit-if-one-screen` doesn't seem relevant to searching.  Perhaps more explanation is useful other places, I'm not sure.
