### ISSUE TITLE
vscode and atom require -w flag

### ISSUE THREAD

**Issue by bast** [coderefinery/git-intro#219]
When hooking up Git with vscode or atom (and others?), the editor needs to be set with -w flag to wait for the editor to close, otherwise Git aborts the commit with an empty commit message.

**Comment by rkdarst** [comment]
@essihe, can you give me a hint on how vscode should be configured...?

The installation instructions are here, I'm not sure if this should go there or in this lesson... https://coderefinery.github.io/installation/

**Comment by bast** [comment]
What I meant here is that in `~/.gitconfig` it may not be enough to say `editor = vscode` but rather `editor = "vscode -w"`.

**Comment by essihe** [comment]
> @essihe, can you give me a hint on how vscode should be configured...?
> 
> The installation instructions are here, I'm not sure if this should go there or in this lesson... https://coderefinery.github.io/installation/

I'm not sure I understand what is wrong. To use Git with vscode I didn't have to configure anything, comes automatically when making changes in a repository.

**Comment by bast** [comment]
This ticket here is about the situation where somebody is working in the command line (during workshop) but prefers to edit commit messages with vscode. I have seen in 1-2 cases that without the `-w` the command line opens vscode for few milliseconds but then closes it again before one has the chance to write the commit message. If one works within vscode, not the command line, then this problem is not relevant.

**Comment by bast** [comment]
I think this is dealt with now in our configuration videos.
