### ISSUE TITLE
staging episode: refactoring

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/git-intro#231]
This is basic comments on my proposed refactoring of the staging episode.

Three learning objectives:
- when is staging useful
  - when not / alternatives (git commit -p)
- how to do it
- staging for conflict resolution

Proposed changes:
- first: the top example seems a better case for `rebase -i`, make it simpler: `add features A, B, C` and `add feature A`, `add feature B`, `add feature C`.  A simplifed version of the current one is food for thought: when you are flipping orders, should commits be grouped?

- then introduce interactive staging, `git commit -p`, as solution to above. Currently it is optional, but this seems more useful than paging to solve the problem above: anyway you need `-p` if you have different changes in the same file.  Have a quick example.

- Then roughly going through the rest like it is, but simplify where possible.

What do you think, does the above fit in with our previous design?  Does it actually simplify?  (One thing I notice is that I personally emphasize staging for splitting changes into two commits, not saving good code while still incrementally working, but I will mention that, too)

**Comment by bast** [comment]
About staging for conflict resolution: we may have a timeline problem since conflict resolution comes later.

**Comment by bast** [comment]
> Proposed changes:
> 
> * first: the top example seems a better case for `rebase -i`, make it simpler: `add features A, B, C` and `add feature A`, `add feature B`, `add feature C`.  A simplifed version of the current one is food for thought: when you are flipping orders, should commits be grouped?

Good plan to simplify it.

> * then introduce interactive staging, `git commit -p`, as solution to above. Currently it is optional, but this seems more useful than paging to solve the problem above: anyway you need `-p` if you have different changes in the same file.  Have a quick example.

I agree.

> * Then roughly going through the rest like it is, but simplify where possible.

Simplify as much as possible. I would also make "States of a file" more of a reference than something we need to understand. I don't think it's possible to absorb it in the 3 minutes we usually spend on this.

I am not sure we still need to keep the question "What types of problems can occur in other version control systems without a staging area?" Most participants we have do not arrive from a different VCS. This made more sense 10 years ago.

**Comment by rkdarst** [comment]
> About staging for conflict resolution: we may have a timeline problem since conflict resolution comes later.

Oh... this isn't exactly a learning objective, but to me, the reason we *have* to say something about staging is that `add` is mandatory in conflict resolution later.  So we don't teach "staging for conflict resolution" here, but just enough to understand `git add` during that episode.

I saw that history inspection is expanded by 10 minutes.  I propose that the time comes from this episode: it becomes 10 minutes shorter.

**Comment by bast** [comment]
Thanks for clarification! I will try to use 60 minutes (with breaks) for history inspection in total: https://coderefinery.github.io/2020-04-07-online/

**Comment by rkdarst** [comment]
Is this diagram sufficiently simple and good to introduce the commands:
http://rkd.zgib.net/hidden/staging-basics.svg

**Comment by bast** [comment]
Looks good but nitpicking comment could be that git checkout does not produce an edited state but an unedited state. It is often used to undo the editing part.

**Comment by rkdarst** [comment]
True.  I'd like to avoid having four states, even though that is most technically correct.  Can you think of a name that represents it well?

what about "working dir" ?  That's more like it... it's not a file state, but file location.

Version also updated to include the relevant diff commands.

**Comment by bast** [comment]
I had same thoughts. Also want to avoid 4 states. Thinking more ...

**Comment by bast** [comment]
Working dir is better. Current figure is the best I could come up with with 3 states. I am wondering whether the problem is visualizing states (since the comitted becomes the next working dir). I will try to sketch an alternative version which does not emphasize states but the process using images instead of boxes, a bit a la https://github.com/coderefinery/git-intro/blob/gh-pages/img/octopus.jpeg

**Comment by rkdarst** [comment]
OK, yeah - a nice picture like that would be good.  I think the "process" emphasis is right - our goal isn't to described the states but these six command and how they are the logical inverses of each other - and add+commit = commit.

I think I'll use this for tomorrow and we can improve later.  source is svg and edited with inkscape.

**Comment by bast** [comment]
I was always "bothered" by the 4 states cycling back into itself although the project is evolving in time. I will sketch a figure using images and share for feedback.

**Comment by bast** [comment]
In my understanding this refactoring is now done. I would still like to update the figure but this is followed up in #216.
