### ISSUE TITLE
undoing episode: refactoring

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/git-intro#232]
For transparency, here is how I plan on improving the redoing episode:

Rename to "undoing and recovering", perhaps - I'm not sure if it is good.

Three tasks should be able to be done after this:
- when you have made changes but not committed yet, how to get back to known state (checkout -f, reset --hard HEAD)  (this is new, but an side note at the start.)
- when you have made commits on a branch, and want to go back.  reset --hard
  - when you want to go back to a branch, but keep current state of working tree: --mixed
- change the last commit you just did (commit --amend)
- revert

Though I have a feeling this is too much - can it be reduced to three? What order should these be in?

Proposed outline / notes:
- Make it more concrete with the focus towards "getting back to a known state", seems sort of abstract in the introduction now.
- Otherwise, similar in spirit to now, I'm a bit too tired now to say more...

**Comment by bast** [comment]
I think it's good to have all of them even though we will not be able to discuss all of them. I find revert and undo uncommitted changes more important than the other two (incomplete commits are less of a problem than over-complete commits, too many commits less of a problem than too few).

These two are super common but we need to discuss them after we have introduced branches:
- committing to the wrong branch
- staged changes while on the wrong branch (typically not a problem but still participants are unsure what happens then)

**Comment by bast** [comment]
Maybe we need an undoing episode before branches and one with branches.

**Comment by rkdarst** [comment]
I'd like to include this xkcd, as an exapmel of what this lesson aims to avoid (deleting and resyncing): https://xkcd.com/1597/

agree/disagree?  It is CC-BY-NC 2.5, so not strictly compatible.  How should it be included: hotlinking, embedding in git source, regular link and don't show it in the lesson itself...

**Comment by bast** [comment]
Agree :-) No strong preference about how it should be included but hot-linking or regular link should be safe.
