### ISSUE TITLE
git graph is first mentioned in 05-undoing but alias is in 06-branches.md

### ISSUE THREAD

**Issue by annefou** [coderefinery/git-intro#248]
When we re-organized the lesson, it seems that we forgot to move `git graph` definition in 05-undoing.md

**Comment by rkdarst** [comment]
I thought it also used to be introduced in the basics episode, but
can't find any evidence of that anymore.  I'd personally start using
it as soon as possible because it provides such concise summary
summary of history and current branch, and it's natural to keep using
it later.

**Comment by bast** [comment]
I think "undoing" (better name/content possibly: "recovering from mistakes") could/should be after branching/merging. This will not only allow showing how to undo branch mishaps, it might also feel better to do a bit more before we start undoing. It would also solve this problem here in passing.
