### ISSUE TITLE
`git commit -p`: unclarity in the manuals

### ISSUE THREAD

**Issue by bast** [coderefinery/git-intro#249]
feedback from online workshop:

> `git commit -p`: unclarity in the manuals, doesn't mention what happens when changes are split between a few lines

**Comment by Sabryr** [comment]
1. At this stage, may be not use shorthand. 
We are not taking about " git commit --interactive" here, although title is "Interactive committing". May be re write this with an example using "git commit --patch"
 
2. /home/Git/test-branch $ git commit -p
diff --git a/4.txt b/4.txt
index b8626c4..6206384 100644
--- a/4.txt
+++ b/4.txt
@@ -1 +1,7 @@
 4
+line 2
+line 3
+line 4
+line 5
+line 
+
(1/1) Stage this hunk [y,n,q,a,d,e,?]? 
I d not see "s (split) if there are several" in my git

**Comment by bast** [comment]
Split option is not offered if the hunk is too short AFAIU.

**Comment by bast** [comment]
Stealing the issue.

- I agree about better using the longer name for the flag.
- For me this is interactive committing since we are in an interactive dialogue with Git on what to commit.
- Agree that we need a bit more info there. Working on it ...

**Comment by bast** [comment]
The instructions say that the changes must be separated by at least a blank line for this to work. Also I find the instructions now rather clear. But changing to long name.
