### ISSUE TITLE
history inspection: add solution and maybe different example

### ISSUE THREAD

**Issue by bast** [coderefinery/git-intro#250]
Feedback from online workshop:

> however your exercises could show the desired output so we could figure out if our input was correct. The message for grepping the text ended in vague 'FAIL' message so few of us thought that it didn't work

**Comment by Sabryr** [comment]
Was there any specif lesson/example mentioned ? it seems this might have been the archaeology lesson 

/home/Git/git-intro $ git grep grep
_episodes/10-archaeology.md:  - "`git log/grep/annotate/show/bisect` is a powerful combination when doing archaeology in a project."
_episodes/10-archaeology.md:### 1. `git grep` to search through the repository
_episodes/10-archaeology.md:With `git grep` you can find all lines in a repository which contain some string or regular expression.
_episodes/10-archaeology.md:$ git grep sometext
_episodes/10-archaeology.md:$ git grep -i fixme
_episodes/10-archaeology.md:While `git grep` searches the **current state** of the repository,
reference.md:* `git grep`: search for patterns in tracked files

**Comment by bast** [comment]
Yes that is the archaeology episode exercise.

**Comment by bast** [comment]
Stealing the issue ...
