### ISSUE TITLE
consider merging "Using the Git staging area" and "Undoing things" and move to after branching/merging

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/git-intro#264]
branching/merging is more important to cover well, so staging area and undoing episodes should perhaps be merged and moved to later and possibly made optional

**Comment by bast** [comment]
Same feeling here. We don't need to merge them, since they can be interesting on their own but either less focus or optional and perhaps better later in the course.

**Comment by Sabryr** [comment]
I am of different opinion on this. The safe to use resert, checkout and the reset, revert (non hash changing)  commands I selected today are important part of the basic git usage. It also provide a way to the meaning full commits that we talk about. Some rearrangement needed to to maintain the flow. 
i.e. it is important to show some undo at this stage.

**Comment by bast** [comment]
I think we should still show undoing but I think we show too little "doing". At the end of day 1, participants often do only 3 commits.

**Comment by bast** [comment]
This week we will try a workshop without these episodes. I now think that we should not merge them and we should keep them, but we should move them after the branching and convert "undoing" to "recovery from common mistakes", see also #217.

**Comment by Sabryr** [comment]
How can we close this issue ? @bast @wikfeldt.  I would propose that we mention this in instructor notes so could be handled according to workshop format ,available time learner  questions. 
I will be taking this part for https://coderefinery.github.io/2021-05-10-workshop/. This will be the last part of the first day. In that case, this does not eat-up time from branching-merging. So as an end of the day lesson this OK?

**Comment by bast** [comment]
I would collect staging area and undoing concerning staging area in one episode but I would not do this episode early in the workshop and I would not spend 45 minutes on it. But I would spend time on explaining the staging area analogies.

Then I would add an episode on recovery from typical mistakes and collect some of the "undoing" into there.
