### ISSUE TITLE
Text needing more clarification 

### ISSUE THREAD

**Issue by Sabryr** [coderefinery/git-intro#265]
1. https://github.com/coderefinery/git-intro/blob/gh-pages/_episodes/06-branches.md
We have three commits (we use the first two characters of the commits) and only one development line (branch) and this branch is called master.  May be "we use the first two characters of the commits " referring to the labels in the diagram

**Comment by bast** [comment]
That sentence seems to be a leftover. It sounds to me like at some point there was an associated graph.
