### ISSUE TITLE
HEAD in branching exercise picture is at a surprising place

### ISSUE THREAD

**Issue by bast** [coderefinery/git-intro#270]
https://coderefinery.github.io/git-intro/06-branches/#exercise-create-and-commit-to-branches

If one follows the commands, then the star `*` and `HEAD` should not be at `experiment`.

**Comment by coandrei** [comment]
This is the patch to solve the issue:
https://github.com/coderefinery/git-intro/pull/277

**Comment by bast** [comment]
Fixed in #277.
