### ISSUE TITLE
there is now no episode 07

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/git-intro#272]
probably because a break was removed from the episode list

**Comment by bast** [comment]
But where is this linked to or referred to? The numbering setup is anyway unfortunate.

**Comment by bast** [comment]
Or in other words: why/where is this a problem?

**Comment by Sabryr** [comment]
commit abccc8710e76b2944a811dbe63e68a019c26b9f7
Author: Radovan Bast <bast@users.noreply.github.com>
Date:   Sun Nov 17 11:37:56 2019 +0100

    rm break episodes
    
    this does not mean we will remove breaks but IMO these episodes
    are not helpful since we need to manage breaks and cannot always
    align breaks on episode boundaries

 _episodes/03-break.md | 14 --------------
 _episodes/07-break.md |  5 -----
 2 files changed, 19 deletions(-)
 delete mode 100644 _episodes/03-break.md
 delete mode 100644 _episodes/07-break.md

**Comment by Sabryr** [comment]
@bast @wikfeldt  I am closing this issue as the episodes removed were in fact breaks. No links broken. Not doing any changes to files names at the moment and we could do it during next episode shuffle. FYI, long time a go this was the alias episode
HEAD is now at 0a5c998 add list of our fav aliases; fixes #74
((0a5c998...)) $ less _episodes/07-aliases.md
