### ISSUE TITLE
Improve example on using `difftool`

### ISSUE THREAD

**Issue by manuGil** [coderefinery/git-intro#329]
The code example on using `git difftool` with meld would be clearer if the command makes reference to the need for a commit hash.

Example:
`git difftool --tool=meld <hash>` 

Exercise: https://coderefinery.org/git-intro/basics/#optional-exercises-comparing-renaming-and-removing

**Comment by bast** [comment]
Good point. This would be more robust since then there is less risk of diffing something that is staged and seeing zero difference.
