### ISSUE TITLE
dollar sign copied from mkdir recipe

### ISSUE THREAD

**Issue by eglerean** [coderefinery/git-intro#333]
In file https://github.com/coderefinery/git-intro/blob/main/content/basics.md when setting up the folder (mkdir recipe) the $ sign gets copied and a learner got confused.

**Comment by bast** [comment]
There seems to be a fix for the copy button and dollar signs but this is beyond this episode and we need to fix it in sphinx-lesson.

Of course we could also get rid of dollar signs but I am not sure whether this will globally help or confuse input and output.

**Comment by rkdarst** [comment]
I almost have a fix, it seems... fixing up a very old sphinx-copybutton pull request (I looked at it at one point but didn't fix, seems urgent now so am fixing...).

**Comment by bast** [comment]
Problem seems solved. Closing.
