### ISSUE TITLE
add git command cheat sheet somewhere at the end 

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/git-intro#36]
we should compile all commands that we use (and maybe some others) in git-intro, git-collab and git-archeology and make a cheat-sheet lesson. not sure if git-intro is the right place to put it, but it then has the advantage that learners see it and can go back to it during the git-collab and git-archeology sessions

**Comment by Sabryr** [comment]
There are quit a few available on-line already, Any suggestion ? or should we compile our own one (this I need more time).

**Comment by bast** [comment]
I think it is a good idea. If we don't manage this time, we do it for the next workshop.

**Comment by wikfeldt** [comment]
yes there are many available online, but we should compile our own based on the material. but for linköping maybe Sabry can just mention online cheatsheets towards the end of the git-intro session, github has a simple one at https://services.github.com/on-demand/downloads/github-git-cheat-sheet.pdf

**Comment by bast** [comment]
Isn't this already done? Where is the cheatsheet now? We could link to it or already do? @rkdarst

**Comment by bast** [comment]
Yes. It is already done and linked here: https://coderefinery.github.io/git-intro/reference/#other-cheatsheets
