### ISSUE TITLE
Emphasis on  decorated  git log instead if showbranch

### ISSUE THREAD

**Issue by Sabryr** [coderefinery/git-intro#37]
The out put of 
git log --graph --decorate --oneline --abbrev-commit
is easier to comprehend than showbranch

So define an alias for this and use it more. 

E.g.
git config --global alias.graph "log --graph --decorate --oneline --abbrev-commit"

**Comment by bast** [comment]
Yeah, let's get rid of the showbranch, it is not intuitive at all.
