### ISSUE TITLE
Detailed day 2 schedule

### ISSUE THREAD

**Issue by dianaiusan** [coderefinery/git-intro#380]
**Day 2**
* 08:50 - 09:00 (10 min) Soft start and icebreaker question
* 09:00 - 09:10 (10 min) Recap and Q&A from day 1
* 09:10 - 12:30 [Introduction to version control (part 2/2)](https://coderefinery.github.io/git-intro/)
    - 09:10 - 09:40 (30 min) [Sharing repositories online - teaching/type-along](https://coderefinery.github.io/git-intro/remotes/#sharing-repositories-online) Dhanya
    - 09:40 - 09:55 (15 min) [Inspecting history - teaching/type-along](https://coderefinery.github.io/git-intro/archaeology/#inspecting-history) Radovan
    - 09:55 - 10:10 :coffee: :walking: :tea: Break
    - 10:10 - 10:40 (30 min) [Inspecting history - breakout room exercises](https://coderefinery.github.io/git-intro/archaeology/#exercise-basic-archaeology-commands) Radovan and ELs/EHs
        1. [Basic archeology commands](https://coderefinery.github.io/git-intro/archaeology/#exercise-basic-archaeology-commands)
        2. [Optional: Git bisect](https://coderefinery.github.io/git-intro/archaeology/#optional-exercise-git-bisect) - to be done if time allows
    - 10:40 - 10:50 (10 min) Summarize inspecting history
    - 10:50 - 11:05 (15 min) [Undoing and recovering - teaching/type-along](https://coderefinery.github.io/git-intro/recovering/#undoing-and-recovering) Dhanya
    - 11:05 - 11:15 :coffee: :walking: :tea: Break
    - 11:15 - 11:35 (20 min) [Undoing and recovering - breakout room exercises](https://coderefinery.github.io/git-intro/recovering/#exercise-revert-a-commit) Dhanya and ELs/EHs
        1. [Revert a commit](https://coderefinery.github.io/git-intro/recovering/#exercise-revert-a-commit)
        2. [Modify a previous commit](https://coderefinery.github.io/git-intro/recovering/#exercise-modify-a-previous-commit)
        3. [Git reset](https://coderefinery.github.io/git-intro/recovering/#exercise-git-reset)
    - 11:35 - 11:50 (15 min) Summarize undoing and recovering and discussion and mention that staging area exists
    - 11:50 - 12:00 :coffee: :walking: :tea: Break
    - 12:00 - 12:25 (25 min) [How much Git is neccessary?](https://coderefinery.github.io/git-intro/level/#practical-advice-how-much-git-is-necessary) Radovan
    - 12:25 - 12:30 (05 min) Feedback & What will we be doing tomorrow?

**Comment by blindij** [comment]
PR #387 closes this issue
