### ISSUE TITLE
git graph alias is not underlined as much as it could be

### ISSUE THREAD

**Issue by frankier** [coderefinery/git-intro#382]
The formatting of the git graph alias does not visually draw enough attention to it. Although the instructor did underline it, we nevertheless had a few people who hadn't set it. As possible reason for this is the material makes it look like an optional extra.

In https://coderefinery.github.io/git-intro/branches/#now-we-want-to-do-this it is introduced with a "Note" box. Visually, this sort of looks like optional material. Important/red formatting may be appropriate here. The title is "A useful alias". Again, this sounds like it's optional and not a prerequisite to the following material. The first few times it is used, it can be mentioned as "git graph alias that we created above" where "created above" is an anchor link to the box with the definition.

**Comment by rkdarst** [comment]
Very true, it is extremely under-emphasized!  https://github.com/coderefinery/git-intro/pull/383 should make this better in both styling and wording.
