### ISSUE TITLE
Probable typo with semantic implications (stage/state)

### ISSUE THREAD

**Issue by wmotion** [coderefinery/git-intro#385]
In https://coderefinery.github.io/git-intro/guide/ at

https://github.com/coderefinery/git-intro/blob/ddc94079b895490c8f2c363a2bdc59eea2e1df14/content/guide.md?plain=1#L34

>different stages a file can have

should possibly become

> different **states**  a file can have

or, equivalently according to definition 3 in https://www.dictionary.com/browse/status,

> different **statuses**  a file can have

Boldface is only for emphasis here.

**Comment by bast** [comment]
Thanks!
