### ISSUE TITLE
Many people struggled installing opendiff on macOS

### ISSUE THREAD

**Issue by bast** [coderefinery/git-intro#392]
- is there a different but similar tool?
- or should we mark that this is not essential to have?

**Comment by MatiasJJ** [comment]
I just found out I have this `opendiff` installed. Did not know. Have no recollection of installing it. 

At least here they say:
```
The good news is that XCode provides a GUI tool called FileMerge, which is also known as opendiff from the command line. You do have to agree to the Xcode/iOS license, which requires local admin privileges, to use this tool.
```
https://www.rubycoloredglasses.com/2017/08/opendiff/#:~:text=The%20good%20news%20is%20that,opendiff%20from%20the%20command%20line.

**Comment by bast** [comment]
Closing. I don't know what to do about it. If we need to adjust, then in the install instructions.
