### ISSUE TITLE
"sharing repos online" problems

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/git-intro#393]
- remote origin already exists
  - I'm not sure just where this came from.  recovery box and not deleting?
- Pushing: remote contains work that you don't have
  - I am not sure where this comes from, but it is common

At least one person might have tried linking yesterday already(?)

**Comment by bast** [comment]
Second problem comes from people clicking on "add README" or "add license". Seen many times. We need a recovery there.

**Comment by bast** [comment]
What do you think is better recovery to offer for problem 2?
- force-push with an explanation what it does and why it is to be used with care?
- delete the github repo and re-create it?
- rename the github repo and create a new one and show later how to delete?

**Comment by samumantha** [comment]
I'd say whatever is closest to real life.
 Starting again from scratch (deleting and recreating) is maybe what any beginner could find out by themselves and what one would start with when in that situation by oneself?
But force-push is maybe better; to teach something they might not think of and get the possibility to talk about the "use with caution"?

**Comment by rkdarst** [comment]
I'd also vote for force-push.  It's most similar to what I would do, easiest, and all.  The warning probably isn't too hard: "if it's a brand new repo, it probably is always fine to do this.  For something with already work, don't do this unless you are very sure what is happening."
 and yes, I do it semi-often on branches and stuff.

Perhaps another option is "git pull" and hope that these initialized files aren't overlapping.  It might not work if default upstream is set.

**Comment by bast** [comment]
Going for force-push solution. Thanks!
