### ISSUE TITLE
Simplify the Git intro by minimizing new concepts directly not relevent for git

### ISSUE THREAD

**Issue by Sabryr** [coderefinery/git-intro#4]
1. Change the python example to  a simple text file or a shell script (e.g just echo "sabryr added this line" ) and compare with the comments. Then emphasize the importance of the comments  when the changes are not trivial. 
Reason:
A. This is a git intro and remove the mentioning of Python
B. Diff is easier to comprehend when it is just text, or simple script

*This is a suggestion and if someone has a good counter argument I will take it as it is.

**Comment by Jyrsa** [comment]
I'd suggest print statements in Python. probably simpler than a shell script.

**Comment by bast** [comment]
I agree that Python is possibly better (more familiar) than shell script. However we can simplify the Python code. I would remove all the `__name__` stuff. If you have never coded Python, then this is just confusing. I also like examples with text files but I personally find examples with "radovan added this line" boring. I would go for a recipe or a poem or a song text.

**Comment by bast** [comment]
We need to replace/simplify this example:
```python
# i am a comment
from hello import say_hello
if __name__ == "__main__":
    say_hello()
```
