### ISSUE TITLE
Extended title suggestion

### ISSUE THREAD

**Issue by samumantha** [coderefinery/git-intro#405]
Introduction to version control - Why you should care about version control and how it is done

Version control is maybe a bit abstract for researchers?

**Comment by bast** [comment]
"Introduction to version control - Why we want to track versions and how it is done" ?

**Comment by samumantha** [comment]
or:  "how to go back in time when things were working " :D

**Comment by bast** [comment]
Yes! "Introduction to version control - Why we want to track versions and how to go back in time to a working version" ?
