### ISSUE TITLE
add visuals in addition to the commands

### ISSUE THREAD

**Issue by dianaiusan** [coderefinery/git-intro#426]
While creating different files and commits, to would be good to see how the structure of the local directory, the index and commit tree are changing. The Git book has some really nice graphs that we can take inspiration from. I'd be very happy to help out with this.

**Comment by bast** [comment]
Thank you. All help welcome here.

**Comment by bast** [comment]
This is somehow related to #459. I will follow-up there. This here is a good idea but the lesson changed in the meantime and we are also one year later.
