### ISSUE TITLE
pdf version of webpage

### ISSUE THREAD

**Issue by linc0380** [coderefinery/git-intro#429]
It would be superb to have a one-file pdf version of this wonderful documentation.

**Comment by rkdarst** [comment]
Here are the PDFs for the two first-week lessons:
* https://coderefinery.github.io/git-intro/_static/lesson.pdf
* https://coderefinery.github.io/git-collaborative/_static/lesson.pdf

These are still relatively new, so do you have any comments on them?  Are they useful for reading?  Any problems that should be fixed?  Etc.  (for example, in git-intro page 2 I notice a black-background screenshot that would probably use a lot of ink.  But then again there's a lot more in there, too.  Is that a problem?  Is it OK that it even has the optional lessons?  No table of contents?  Formatting OK?  etc.)

**Comment by bast** [comment]
PDF is now generated to https://coderefinery.github.io/git-intro/lesson.pdf

I wonder how we can best link to it from the material ...
