### ISSUE TITLE
Feedback/wishes from march '24 workshop: More illustrations

### ISSUE THREAD

**Issue by samumantha** [coderefinery/git-intro#459]
From Day 1 feedback of March 24 workshop: It may be easier for beginners to understand the new vocabulary if you have additional illustrations showing the differences/similarities between e.g. repository, branch, fork, clone etc. oo

**Comment by bast** [comment]
These places could use an illustration:
- Fork: https://coderefinery.github.io/git-intro/browsing/#creating-a-copy-of-the-repository-by-forking
- Branch and commit: https://coderefinery.github.io/git-intro/commits/#exercise
- Merge: https://coderefinery.github.io/git-intro/merging/
- Clone: https://coderefinery.github.io/git-intro/local-workflow/
- Publishing own work as repo: https://coderefinery.github.io/git-intro/sharing/

**Comment by samumantha** [comment]
Awesome, I could draw possibly draw something during this week. Will add drafts for discussion .

**Comment by bast** [comment]
To avoid possible accidental double-work, I am working on this.

**Comment by samumantha** [comment]
Good luck! I didn't come up with anything useful :/
