### ISSUE TITLE
is .gitignore presented somewhere in the new lesson configuration?

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/git-intro#461]
One of the more important things, we got a question about it.

**Comment by rkdarst** [comment]
I guess "git status" is also needed here.

**Comment by bast** [comment]
- .gitignore: https://coderefinery.github.io/git-intro/what-to-avoid/
- git status: #451

**Comment by bast** [comment]
At some point I thought it would be fun to add it to the starting repo. But GitHub allows you to add files via web interface even when they are gitignored. So I decided to not go into that and rather leave it to the end of day 2.
