### ISSUE TITLE
Timings from Online workshop March 2024

### ISSUE THREAD

**Issue by bclaremar** [coderefinery/git-intro#467]
Possibly to be implemented in future schedules and instructor notes for the lessons missing that information today.
Source: https://github.com/coderefinery/2024-03-12-workshop/blob/main/video-editlist.yaml

## Schedule Day 1

Times here are in CE(S)T.

- 08:50 - 09:00 (10 min) Soft start and icebreaker question
- 09:00 - 09:20 (20 min) Welcome and practical information
- 09:20 - 09:25 (05 min) [Intro to day](https://coderefinery.github.io/git-intro/)
- 09:25 - 09:35 (10 min) [Motivation](https://coderefinery.github.io/git-intro/motivation/)
- 09:35 - 10:25 (30+10 min) [Copy and browse an existing project](https://coderefinery.github.io/git-intro/browsing/)

- 10:05 - 10:15 (10 min) Break

- 10:25 - 11:00 (35 min) [Committing changes](https://coderefinery.github.io/git-intro/commits/)

- 11:00 - 12:00 (60 min) Lunch Break

- 12:00 - 12:55 (15+40 min) Recap + [Merging changes and contributing to the project](https://coderefinery.github.io/git-intro/merging/)

- 12:55 - 13:00 (5 min) Break

- 13:00 - 13:30 (20 min) Demonstrating conflict resolution, Q&A, feedback, and what will we be doing tomorrow?
  - This time also:
  - create new branch (coderefinery/other repo) and open pull requests 
  - look at pull requests
  - try to merge conflicting
  - summary
  - Q/A
  - feedback and more Q/A
  - outlook for tomorrow

## Schedule Day 2

Times here are in CE(S)T.

- 08:50 - 09:00 (10 min) Soft start and icebreaker question
- 09:00 - 09:10 (10 min) Intro talk
- 09:10 - 10:10 (50 min with 5 m Q/A after break) [Cloning a Git repository and working locally](https://coderefinery.github.io/git-intro/local-workflow/)

- 10:00 - 10:10 (10 min) Break

- 10:15 - 11:00 (45 min) [Inspecting history](https://coderefinery.github.io/git-intro/archaeology/)

- 11:00 - 12:00 (60 min) Lunch Break

- 12:00 - 12:05 (5 min) Recap etc...

- 12:05 - 12:45 (40 min) [How to turn your project to a Git repo and share it](https://coderefinery.github.io/git-intro/sharing/)

- 12:45- 12:55 (10 min) [Practical advise](https://coderefinery.github.io/git-intro/level/)

- 12:55 - 13:05 (10 min) Break

- 13:05 - 13:30 (25 min) Q&A, feedback, and what will we be doing tomorrow?
    - This time also .gitignore
    - branch design
    - what to avoid
    - feedback and more discussion
    - preparation for next day

**Comment by bast** [comment]
Thanks! I am updating the instructor guide which will be a compromise between the two versions since we cannot shorten breaks. But I like the additional detail about recap.

**Comment by bclaremar** [comment]
Good!
The recap was what was covered according to the video edit list, to be clear!
