### ISSUE TITLE
Consider removing the --amend example

### ISSUE THREAD

**Issue by bast** [coderefinery/git-intro#58]
Modifying commits can be problematic. Also the example of adding the author name is strange for me since Git knows the author of the commit.

**Comment by Sabryr** [comment]
Yes, having author is strange. But I like the --amend as I see it, it is harmless way to change the commit message. e.g. spelling, forgot to add about the second file etc,,

**Comment by Sabryr** [comment]
I agree, I added that warning  (and will learn about push later)
