### ISSUE TITLE
Add a "time -->" arrow to the commit graphs

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/git-intro#59]
It's obvious to us, but make it clear which direction time flows.  These graphs are the best way to make the abstract ideas concrete, and they need all they help they can get - at every instance.

Also, the output from "git graph" has time flowing up, most of our pictures have it going right or down.  It would be nice if they could be unified, but it's not worth it - a clear time arrow is enough.

I think I had another idea about these diagrams but can't remember.

**Comment by bast** [comment]
I really like if people self-assign. I personally like if "assigned to X" means "X is working on it. So I will unassign and self-assign once I start working on it.

**Comment by wikfeldt** [comment]
i'm not sure this is needed. The commits are usually labeled like m1-m2-m3-... which indicates in which order they were created. If a time arrow were to be introduced, it probably should not be between the commits (giving the wrong impression that one can only go forwards and not backwards) but rather e.g. in the bottom left corner. 
But I don't consider this to be important, more important would be to clearly show somewhere that `git log` and `git graph` give reverse chronological order

**Comment by bast** [comment]
I agree. We never had this and I don't think it has been a big problem. I want to close this issue. Do you want to follow-up with your suggestion in a separate issue?

**Comment by wikfeldt** [comment]
I'll close this issue and add to the instructor guide that chronological order in git log output should be explained
