### ISSUE TITLE
Suggestion for bigger restructuring

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/git-intro#60]
While this material is good, I think it could be made even better by a restructuring.  There are two audiences which I think aren't served well (everything in this issue, I have said before but I don't think is written anywhere):
- Those who already have sort of used git (we start with stuff they already know, git init, git add, and so on)
- Those who know nothing about version control.  Very soon, they go off to git init, git add, and so on and probably don't have a big picture.

I've given some git intros to academic courses, and the usual problem is some people know a lot already, and can easily teach others if others became interested.

Once I tried to write a better plan, where the why and social design are front-loaded, and then the "how" is later.  It went something like:

- Why code becomes a disaster without (lots of examples here, throw in some of the famous comics about it)
- Use github web interface to see an existing project: explore the history, see contributors.  Give some exercises like "this line has a bug: who did it and when?", "how many contributors", "find version on this date".
- Ideally, use browser to make a commit on existing project, maybe even a merge request (it's easy in browser, and shows cool stuff).  So, bring in some of the "git in the browser" stuff, but less structured, just to show people nice things.
- Ideally something from git branch design.  Now the details, but there are good stories there and when I saw this, it felt like good motivation finally came.
- Then switch to "git init" and so on...

All the intro parts is relatively non-technical so could be done in an hour maybe.  I'm sure it would save at least an hour later.

Additional ideas:
- have people contribute to existing project first.  I guess this is a fairly common case and many people probably would start here first anyway (just for the web browser part)

If not used here, I would adapt these to either git-in-the-browser or some "git for normal people" type talk.

**Comment by bast** [comment]
I really like that we start out in the browser to get a taste before we go into the "dryer" `git init` to get deeper understanding. In other words we will start out with a jam session on the web, then we practice a bit scales on our local instrument, then we regroup again in day two and play orchestra music together.

**Comment by bast** [comment]
Idea for the in-browser tasting:
- We start with an existing repo that contains a couple of commits and two branches with some easy code.
- The project contains several obvious issues (bug in code, misleading comment, typo in documentation, missing license file, outdated usage example).
- We browse it a bit and our first challenge is to figure out when exactly the bugs were introduced.
- Then instructor shows how to fix one of the problems in the browser.
- We split into groups and each group fixes one problem and files a pull request.
- The goal of this is to get a bit of a taste and to see that we can work on the same file in parallel while recording traceable snapshots.
- Project contains several files so that we see that there is a version uniquely identifying the state of the entire project.

**Comment by bast** [comment]
More points:
- All is done in browser.
- It's perhaps a bit magic but we will explain what is going on later.
- Master branch is protected (we start with good defaults).
- We also browse commit diffs to get a feel for what a commit is.

**Comment by Sabryr** [comment]
In light of new Github politics, should we shift this much focus to the web (in this case Github) rather than universal Git stuff ?

**Comment by bast** [comment]
I am not sure. But the goal would not be to explain GitHub in the first 30 minutes but to start with an existing repository. And existing repositories are most likely GH repositories. The goal would be to get a taste and motivation. I always found the `git init` start a bit harsh and dry without seeing the bigger picture first. Of course we will comment on the geopolitical situation after last weekend and of course we would emphasize that we could do the same thing on GL and friends. And eventually we might move over to GL but we have no time to do it now.

**Comment by bast** [comment]
The point is that existing Git repositories are these days almost never "plain" Git repositories without any web around it. First contact point might be the web.

**Comment by bast** [comment]
Previously we start from zero, build something up, and hope that eventually people realize that they need it. My goal here (and this is not only my idea, credits to Richard) would be that everybody understands "aha yes I really need this, this is relevant for me, I need to listen", *before* we do the first Git command in the terminal.

**Comment by rkdarst** [comment]
Yes, basically, the point isn't to teach github (even a week ago, we
would want to minimize the importance of github itself), but because
it's a good way to visualize a lot of people working on a project
together - they can at least see history, annotate of files, and the
way someone can make a branch and pull request and why this is nice.
Then the git commands make sense.

I think this is a good idea, and the trick is a good example and
making it as brief as possible.  One possibility is the coderefinery
repository for the lesson itself... also it's a case where making a PR
through the browser actually makes some sense.

**Comment by bast** [comment]
Should this be demo only or already an exercise?

**Comment by bast** [comment]
I would probably like to show something else than the lesson repo because I would like to demonstrate the situation that we spot a bug and want to see when it was introduced - this is not very relevant for lesson repo.

**Comment by bast** [comment]
Also I want to show something that has a `master` branch, not `gh-pages` branch to connect better to the terminal work.

**Comment by bast** [comment]
After some thinking I will draft an example repo that we will live-modify: all instructors will make a change concurrently, one of them (the presenter) will do one change on the screen. Then we browse a bit the history. Also experienced participants can already join. The reason for this is that it would be nice to show 1) that one can work concurrently and 2) a project with multiple authors. 2) is hard for me to create on my own :-)
