### ISSUE TITLE
Instructor guidelines

### ISSUE THREAD

**Issue by Sabryr** [coderefinery/git-intro#61]
Bullet points for each lesson, each episode,
Collecting experience - lessons learned. 
Go through the git issues.

**Comment by rkdarst** [comment]
Create a "cheatsheet" on the board as you go (possibly similar to the online visual git cheatsheet - I referred to this).  After each command is introduced, write it on the board.  After each module, make sure you haven't forgotten anything.  Re-create and expand in future git lessons.  We should try to make a cheatsheet based on our git lessons, too.

![image](https://user-images.githubusercontent.com/6877977/40658682-ae5f9f38-6354-11e8-9b90-ffaf767694dc.png)

**Comment by rkdarst** [comment]
I had two things I was constantly repeating to  the point of becoming a meme:

- once you `git add` something, it's almost impossible to lose it.
- always check `git status`, `git diff`, and `git graph` before and after every command until you get used to things.  These give you a clear view into what is going on, the key to knowing what you are doing.  Also that `git graph` is direct representation of what I am drawing on the board.
