### ISSUE TITLE
Motivate better

### ISSUE THREAD

**Issue by Sabryr** [coderefinery/git-intro#63]
Motivate better, include selling points, why before how

**Comment by Sabryr** [comment]
IMO: For git-intro/01-motivation/, motivation good, other lessons checking.

**Comment by bast** [comment]
The motivation needs to be shaped to researchers who may not be interested in infrastructure details.
Examples:
- that Git is fast does not matter to people
- that Subversion is centralized does not matter unless we motivate from the backup angle
- we need to turn this around and motivate that installing a Git repo is less work than setting up a service in Subversion
- "powerful": does not matter and is scary perhaps

Distill the essence for students and researchers, try to convince them in 10 minutes. Emphasize reproducibility.

**Comment by bast** [comment]
Put emphasis on why version control. Not so much on why Git. Too often I have seen that we spend minutes motivating Git compared to other VCS and we don't mention reproducibility even once.

**Comment by rkdarst** [comment]
Compare to dropbox/google drive.  These let you get old versions but in a much less useful way - snapshots of files, not directories.  Maybe add more horror stories (at least talk about them).  There are some good webcomics about this.

Otherwise few things to change.

**Comment by rkdarst** [comment]
The motivation section can also include more direct analogies to research.  In particular, think of answering the question "how does one apply this my work?"  This can even be made into the "how to best use git for research, if you already know some version control and don't want to go into the technical stuff".

My goal would be that this section and a new "git practical tips" section would be good for my use case of "how to use git for this course / science / ..., if I don't need to start from the individual git commands".

**Comment by bast** [comment]
I agree with this suggestion (also to have a Git practical tips section). Working on it now.

**Comment by bast** [comment]
Practical tips suggestion followed up in #87.
