### ISSUE TITLE
Diagram with working directory, staging area, and .git arrives too early

### ISSUE THREAD

**Issue by bast** [coderefinery/git-intro#70]
We should start typing and explain then. I think we explain concepts a bit too early.

**Comment by rkdarst** [comment]
I put these on the board early and used it as a running diagram, I was constantly updating it and showing "this is what git checkout does".  I used this more than the diagrams in the lessons.  Also connected this to "git graph" always.

**Comment by bast** [comment]
I believe this is solved. Both by moving text and with now good instructor guides.
