### ISSUE TITLE
Simplify recipe example, too conflict-prone

### ISSUE THREAD

**Issue by bast** [coderefinery/git-intro#73]
- Make very clear which lines to modify and which not and why
- Consider risk with newline characters, perhaps do not modify lines at the end of the recipe?

**Comment by rkdarst** [comment]
Modification should be on first line and last line.

Nano might add implicit newlines at the end!

**Comment by bast** [comment]
Since there may be implicit newlines added at the end I think we should not edit the last line but some lines in-between. If nano adds a newline, it adds it either on one branch or on both branches but in both cases this should not generate conflicts.

**Comment by bast** [comment]
Closed by #108.
