### ISSUE TITLE
Suggestions: Basics

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/git-intro#75]
- [x] First section can probably be shorter, should have been motivated before.  Basic mention of `.git` and that it doesn't do anything unless you want.  Also multiple interfaces
- [x] "mental model of git" - 3 headings can be made much shorter (#69, #70).  Some basic intro of the snapshotting, and making a basic git graph would be good.  Staging is maybe useful.  Other things can mostly be removed.  Some conceptual stuff good.
- [x] For maximum simplification, remove "git add" during normal commits and use "git commit" only.  But this is probably not worth it.
- [x] Agree, undoing things come too early.  
- [x] Introduce "git graph" alias earlier - this is good because the output matches what we are showing on the board and on the diagrams.  Show the output of this all the time.
- [x] Undoing section too early (#72).  But some certain parts of that are OK.  Actually maybe it's not too early - just focus it a bit more.
- [ ] `revert` vs `checkout` is confusing, even to me.  Consider this in the undoing section.
- [x] different meanings of checkout comes too early.  Do note it's confusing and we will come back to it later.
- [x] Best practices: these are good, but maybe to another module?  Or inlining more.  I don't really know how to change, probably just leave it.

**Comment by bast** [comment]
I am ticking off issues that are taken care of in past or present PRs.

**Comment by bast** [comment]
Git graph followed up in #99.

**Comment by bast** [comment]
Revert/checkout followed up in #113. Closing.
