### ISSUE TITLE
Split out practical tips into a separate tips section(s)

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/git-intro#76]
Create a separate tips section, maybe several to go in phases.  These will be useful for presenting what to do with git without going into details about how.  Useful for certain forms of presentation.  This should especially connect with scientific stories.

Maybe this would make too many sections... but that's probably not bad.

**Comment by bast** [comment]
Merging with points from #87:
- how to best use git for research, if you already know some version control and don't want to go into the technical stuff
- Leading question: "how does one apply this my work?"

**Comment by rkdarst** [comment]
#164 should be re-done, after figuring out why the title didn't work.

**Comment by rkdarst** [comment]
* Once you commit, it is very, very hard to really lose your code
* Commit early and often
* Always fully commit (or stash) before you do dangerous things, so that you know you are safe.  Otherwise it can be hard to recover.
