### ISSUE TITLE
Suggestions: branches

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/git-intro#77]
- [x] `git graph` can be introduced in the intro lesson (in addition to here).  When speaking, emphasize `git graph` a lot!  Move `git graph` intro here to the very top.
- [x] The first picture doesn't add much compared to the second - use second only?
- [x] "What is a commit?" section.  Can use `git graph` here instead of `git log`.  The `--decorate` emphazes our points.
- [x] #73 - do something to minimize conflicts.  Emphasize only editing the first and last lines?

Not really much more to say here, it worked well.

**Comment by bast** [comment]
Will tick off boxes as I work on #108.

**Comment by bast** [comment]
Closed by #108.
