### ISSUE TITLE
Suggestions: conflicts

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/git-intro#80]
- [x] some of our feedback was asking for more practice on conflicts.  This will probably happen tomorrow, but we could have more exercises here.  Once I made a tar.gz with a repo which you could just unpack and 'git pull' and simulate the conflict.  But clone + merge from the clone works just as well.
- [x] Acknowledge at top that conflicts are scary, but not that bad if you stop and take a deep breath.  Also they are luckily rare.
- [x] Manual resolution paragraph: don't forget to run "git diff" after you have attempted resolution.  There are also a lot of bullet point here - can it be organized some more?
- [x] Resolution using mergetool - at this point we had already resolved so couldn't use it.  Should make another exercise to use this, or show how to reset the successful resolution and then they can try again (may be too complex).
- [x] "theirs" and "ours" strategy: I've never used this before, but seems useful.  Again consider how to let them try this themselves.  And personal note, I guess that the checkout resets all changes to theirs, not just the conflicts?
- [x] The exercise is much later than we we actually resolved it - in class we did it during the "manual method" steps and then had nothing else to do for the rest of the lesson. 
- [x] Avoiding conflicts: discus google drive resolution strategy (very small delta-t and delta-chars) and choosing arbitrarily.  Push early and often - the sooner you merge and push, the less likelyhood you need to do it (others will have to).  But if everyone uses this strategy, then everyone benefits!  Also this paragraph can be broken up some - technical measures, human measures, collaboration measures.  Maybe mention of types of problems there might be - e.g. semantic conflicts that merge but don't work.  Importance of talking!  
- [x] Don't be afraid of git because of conflicts.  You don't get them using other systems because you simply can't do the kinds of things you do in git.  You can take human measures to reduce them.

**Comment by bast** [comment]
Working on it ...

**Comment by rkdarst** [comment]
Another idea: create a repo (or several) with a lot of sample conflicts to resolve.  There could be different methods: via a merge, via a pull, via a rebase, via a "stash pop".  In one of my previous lessons, I had a .tar.gz with repo all set up, you just had to `git pull` to make the conflict.  Similar kinds of things could happen.

All (most?) could be optional or advanced exercises.

**Comment by bast** [comment]
That would be great but I already see that I won't make it for this time but I will keep the idea and possibly move it to an own issue if most of the above gets resolved.

**Comment by bast** [comment]
Suggestion moved to #116 since I will most probably not have time to prepare for next week.

**Comment by bast** [comment]
I think I will not turn ours/theirs to an exercise. This is only a side-note and something I only use once a year or so.
