### ISSUE TITLE
Suggestions: staging

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/git-intro#81]
I thought this was more useful than I expected, but can be refined.

- [x] also formerly (presently?) known as the index.  (or cache, via the option `git diff --cached`)
- [x] Add some examples using the guacamole recipe and remove existing example which doesn't go into detail.  Now we see big collections of commands but not many examples.
  - [ ] by the same token, I used the "homework" section as an in-class example.
- [x] `remove` is not a git command
- [x] `git diff` vs `git diff --cached` - two complimentary things which go naturally here.
- [x] I really like `git add -p`.  Also `git commit -p`.
- [x] We've been using the staging area the whole time - think about what the point of this section is.  It already does have a good point, but if the earlier part of the talk just used `git commit` instead of `git add`, there would be a more direct purpose for it here.  By adding more examples covering everything, this becomes a capstone "practice" session with side-purpose of teaching good staging practices.
- [x] The "git file stages" diagram is different than what I had on the board.  Not saying it is bad, but I found it hard to explain given my flow.  Can this somehow be integrated into my cheatsheet (#61)?

**Comment by rkdarst** [comment]
Not looking at the episode now, but start with description of what can go wrong *without* staging (too many things listed below... pick just the most powerful):

- You do several things at once, but have to commit them at the same time.  Hard to do in some version control systems.
- You have to wait until you are fully done to commit: greater risk of losing things.  What about bugs before you commit?
- You commit things and realize there is a bug.  Maybe you missed something or did too much.  Instead, you can stage, review, then commit.
- Other version control systems have only two places to store data: untracked or committed and might require you commit whole files at once.  A third place gives you some flexibility.

Maybe at bottom (may be too advanced, maybe just say it):
- Staging isn't the only option: you can commit and alter commits to do something similar, if you alter before you push. 
- If you `add -p`, you can also `commit -p` to commit only certain parts, too.

Other staging area analogies (this specific answer + whole question)
https://softwareengineering.stackexchange.com/questions/119782/what-does-stage-mean-in-git/249539#249539

**Comment by rkdarst** [comment]
Brief section at bottom: But staging takes too much time!  Is there a faster way?
- `git commit -p` lets you directly commit specific parts.  Only useful when you are doing simple things.
- `git commit -a` is not recommended, but will do everything at once.  Recommended to run `git diff` first and ask "should this really be one patch?"

**Comment by bast** [comment]
Also make sure that examples are aligned with rest of the lesson (taken from #62).

**Comment by rkdarst** [comment]
I'd say the episode is complete, but there are still many things to do here.  I think putting them here would start to get too busy.  what do you think?

Most of these seem more fitting for a "practical tips" section, which I noticed isn't there yet.  I'd say wait for that until after Oslo, unless you want to now.

**Comment by bast** [comment]
Not closing this yet because there are good points here which are not in material, especially the "what can go wrong if you don't use it".
