### ISSUE TITLE
Suggestions: interrupted work

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/git-intro#83]
This was short but good enough for the point we were at - not really much more to say.

- [ ] Make a quick example of stashing.  I just did this live and it was good.  Make sure that you demonstrate stashing twice.  Also `stash list`.  Also `git graph` and see the stash in that commit.  Stash can be seen as making a quick commit and then backing up.  But also stores staging area.
- [ ] Option2: mention that turning your temp work into a branch isn't that bad - if it's taking this long to make a branch may be a good idea anyway.
- [ ] Aborting the merge was discussed before, but used a different command!  `git reset --hard` is useful enough to show, though, but maybe in a different context (and different section?).
- [ ] examples, examples ?

**Comment by bast** [comment]
Solved in #106.
