### ISSUE TITLE
Introduce git graph alias earlier

### ISSUE THREAD

**Issue by bast** [coderefinery/git-intro#99]
Should be introduced right when we start with branches.

**Comment by rkdarst** [comment]
This is probably solved now.

But, I also have an alias `ll` that is same as `l` (`graph`) but with `--date-order` - it's good if the order is really crazy because of pull requests and reordering some old things before new.  I would *probably* not include it in our alias but thought to mention it.

**Comment by bast** [comment]
I think for our purposes we can leave it out but if the question comes up we can refer to the rich git log features. But you are most welcome to send a patch if you would like to have this in.
